### PR TITLE
Fix issue 30

### LINKED ISSUE #30: gltfUpAxis not part of 3DTiles specification
The conversion of a LAS file to 3DTiles generates a gltfUpAxis property in the tileset.json file. This property is not part of the 3DTiles specification.

### PR DESCRIPTION
**Pull request by peppsac**
2 commits to adapt the code to 3dtiles 1.0 specification.

Fixes #30

### CODE REVIEW

**Comment by Jeremy-Gaillard** [comment]
Since we're removing the glTFUpAxis property, can you add in the export_tileset documentation that we expect mesh geometries to be Y-up? Or change the [parse](https://github.com/Oslandia/py3dtiles/blob/master/py3dtiles/wkb_utils.py#L139) so that it can flip the coordinates, or even change the [SQL query](https://github.com/Oslandia/py3dtiles/blob/master/py3dtiles/export.py#L243) so it does the Y to Z transform.

**Comment by peppsac** [comment]
> Since we're removing the glTFUpAxis propert

To make myself clear: I'm removing it because it's not supported anymore in the spec (cf https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/master/specification#gltf).

> can you add in the export_tileset documentation that we expect mesh geometries to be Y-up?

Yes good idea.

> Or change the parse so that it can flip the coordinates, or even change the SQL query so it does the Y to Z transform.

I believe you meant to write Z->Y transform?

**Comment by Jeremy-Gaillard** [comment]
> To make myself clear: I'm removing it because it's not supported anymore in the spec (cf https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/master/specification#gltf).

Yes, I fully agree with the intent of this PR. We should also check one of these days if any other aspect of the spec changed when AGI pushed the definitive 1.0 spec in august.

> I believe you meant to write Z->Y transform?

Indeed, my bad.

**Comment by peppsac** [comment]
@Jeremy-Gaillard do you think you can fix the sql query to perform the transformation? I'm not at ease with this part of the code yet :)

**Comment by Jeremy-Gaillard** [comment]
I'll take a look at it tomorrow or at the begining of next week.

**Comment by Jeremy-Gaillard** [comment]
Done!

**Comment by peppsac** [comment]
Thanks @Jeremy-Gaillard!

**Pull request merged**
