### PR TITLE
Split README into multiple files

### PR DESCRIPTION
**Pull request by elemoine**
This PR suggests to restructure the documentation a bit. The README now just includes a short description of py3dtiles, and then provides links to separate RST files covering the installation, the CLI usage and the API usage.

I've just changed the structure, not the content. In the future we may want to add screenshots and/or performance tables to the README.

### CODE REVIEW

**Comment by elemoine** [comment]
You can open https://github.com/Oslandia/py3dtiles/blob/readme/README.rst to see what the new README looks like.

**Comment by peppsac** [comment]
Maybe the `Third party assets` section could be moved to the `LICENSE` file?

**Comment by elemoine** [comment]
> Maybe the `Third party assets` section could be moved to the `LICENSE` file?

Good call. I added a commit for that.

**Review by peppsac — APPROVED** [review]

**Comment by elemoine** [comment]
Thanks for the review.

**Pull request merged**
