### PR TITLE
convert colored points from .xyz files

### LINKED ISSUE #53: Support RGB information when converting .xyz files
When converting a `.xyz` file that contains 6 columns (x, y, z and r, g, b), one expects to build a colored 3dtile. However one gets the following trace:
```
Traceback (most recent call last):
  File "/home/rde/src/py3dtiles/py3dtiles/command_line.py", line 38, in main
    convert.main(args)
  File "/home/rde/src/py3dtiles/py3dtiles/convert.py", line 313, in main
    infos = fn(args)
  File "/home/rde/src/py3dtiles/py3dtiles/points/task/xyz_reader.py", line 38, in init
    points[i] = [float(s) for s in line.split(" ")]
ValueError: cannot copy sequence with size 6 to array axis with dimension 3
```
I read the [xyz_reader.py](https://github.com/Oslandia/py3dtiles/blob/master/py3dtiles/points/task/xyz_reader.py#L127) script, and it seems that the color is filled with white triplets.

Considering the RGB info looks possible in `init` function (there is a `RGB` argument), however it is not straightforward in `run` function...

### PR DESCRIPTION
**Pull request by delhomer**
This PR aims at fixing the `.xyz` file conversion when they contain RGB values.

Contrary to the `.las` files, there is no metadata for describing file features. We need to pass the `write_rgb` variable to `xyz_reader.run` function in order to manage this case. I chose to pass it to `las_reader.run` as well, so as to keep the signatures equal (however the parameter is dummy with `.las`...).

The PR fixes #53.

### CODE REVIEW

**Comment by autra** [comment]
Thanks @delhomer!

> Contrary to the `.las` files, there is no metadata for describing file features. We need to pass the `write_rgb` variable to `xyz_reader.run` function in order to manage this case.

If I'm not mistaken, write_rgb is a way to configure the *output*, not a way to deal with missing metadata. We need something else to specify how the xyz file is made (because this is not a standard format). 

Maybe we can start by supporting the [fme interpretation of xyz](https://docs.safe.com/fme/html/FME_Desktop_Documentation/FME_ReadersWriters/pointcloudxyz/pointcloudxyz.htm) only? (so XYZIRGB for a start). It seems to be the same format as CloudCompare?

If we need more flexibility, we could have a cli option for that. WDYT?

**Comment by delhomer** [comment]
> If I'm not mistaken, write_rgb is a way to configure the _output_, not a way to deal with missing metadata.

You probably don't! I believed that `--rgb` did the job, however you're right; I read the doc far too quickly (this argument is passed to the zmq process for setting `write_rgb`).

> We need something else to specify how the xyz file is made (because this is not a standard format).
> 

Exactly, and that is the starting point of my proposal: the current code is only able to manage XYZ columns; that being a problem when handling colored points.

> Maybe we can start by supporting the [fme interpretation of xyz](https://docs.safe.com/fme/html/FME_Desktop_Documentation/FME_ReadersWriters/pointcloudxyz/pointcloudxyz.htm) only? (so XYZIRGB for a start). It seems to be the same format as CloudCompare?
> 

That sounds like a good deal. As a consequence, do we consider `.xyz` files with less than 7 columns as follows:
- 3 columns : only XYZ, we set I, R, G, B to 255
- 4 columns : XYZ+I, we set R, G, B to 255
- 6 columns : XYZRGB, we set I to 255

Or alternatively, do we raise an exception if the input data has wrong dimensions (quite a violent design, isn't it?)?

> If we need more flexibility, we could have a cli option for that. WDYT?

Well... `--be-kind` = accept less-than-7-column files? :)

**Comment by autra** [comment]
3 columns : only XYZ, we set I, R, G, B to 255
    4 columns : XYZ+I, we set R, G, B to 255
    6 columns : XYZRGB, we set I to 255


In my opinion we shouldn't invent missing data and let the viewer decides how it wants to display them (it's its job, isn't it?). With itowns, you can give a  a color to a pointcloud for instance.

so just set what you have, and leave the rest unset. Sounds good for you?

**Comment by autra** [comment]
> Or alternatively, do we raise an exception if the input data has wrong dimensions (quite a violent design, isn't it?)?

How would you define wrong here? We don't really know what's wrong or right concerning xyz, let's be inclusive ;-)

By flexibility, I meant "accept non classic order of columns". But let's not care for that now.

**Comment by delhomer** [comment]
> so just set what you have, and leave the rest unset. Sounds good for you?

Deal. :)

**Comment by delhomer** [comment]
> How would you define wrong here? We don't really know what's wrong or right concerning xyz, let's be inclusive ;-)
> 
> By flexibility, I meant "accept non classic order of columns". But let's not care for that now.

Here the point is that we can't be sure of the xyz file content, especially when the number of columns is unusual (or, let say, different from 7). I will first consider the above hypothesis by leaving the unknown features unset, as said in your last comment.

Commits in preparation!

**Comment by autra** [comment]
Good for me!

**Pull request merged**
