### PR TITLE
docker support

### PR DESCRIPTION
**Pull request by Tofull**
Add Dockerfile to use py3dtiles in a container.

### CODE REVIEW

**Comment by peppsac** [comment]
I'm not sure there's a lot of value in merging a `Dockerfile` in the repository.

@ldgeo, @elemoine what do you think?

**Comment by EricBoix** [comment]
This could be quite useful for
 - hastening deployments (by setting aside a fastidious manual install)
 - enabling developers with a py3dtiles "incompatible" desktop/context: for the time being py3dTiles cannot be installed with Python 3.7 which is currently (10/10/2018) the [homebrew](https://brew.sh/) default version on OSX.
Just my 2cts.

**Comment by elemoine** [comment]
I think it can be useful, so I wouldn't be opposed to it personally.

**Comment by peppsac** [comment]
Using Ubuntu 18 as a base might be overkill: that's a lot of MB to download, to use a python app.

At the very least, it might make sense to use a lighter base image (Alpine?), or even better something based on distroless (https://github.com/GoogleContainerTools/distroless) :)

**Comment by elemoine** [comment]
I've been using Debian slim images. Though they may not be as small as Alpine images…

Also, the Docker-related section will have to be moved into its own rst file, following up on https://github.com/Oslandia/py3dtiles/pull/32.

**Comment by Tofull** [comment]
I updated the pull request according to your suggestions. 
With `python:3.7-stretch` as docker base image, I'm facing the following issue related to pyproj  :

```sh
    error: command 'gcc' failed with exit status 1

    ----------------------------------------
Command "/usr/local/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-91slr0bz/pyproj/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-7uc_2qv1/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-91slr0bz/pyproj/
The command '/bin/sh -c pip3 install -e .' returned a non-zero code: 1
```

Same result with `python:3.6-slim` or `python:3.6-alpine`. But it works with `python:3.6-stretch` docker base image. :triumph:

_____________

> I'm not sure there's a lot of value in merging a Dockerfile in the repository.
>
> -- <cite>@peppsac</cite>

According to the [docker official documentation](https://www.docker.com/get-started) :
- Onboard faster and stop wasting hours trying to set up development environments
- Enable polyglot development and use any language, stack or tools without worry of application conflicts
- Eliminate environment inconsistencies and the "works on my machine" problem by packaging the application, configs and dependencies into an isolated container.

**Comment by delhomer** [comment]
Moved to https://gitlab.com/Oslandia/py3dtiles/-/merge_requests/24

**Pull request closed without merging**
